year: "2024-2025" # 学年
semester: "2"     # 学期，"1" | "2" | "3" 对应秋、春、夏
cookie: ""        # 访问 https://app.buaa.edu.cn/buaascore/wap/default/index，控制台中查询 Cookie
interval:
  min: 60         # 最小冷却时间（秒）
  max: 300        # 最大冷却时间（秒）
